apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo
  template:
    metadata:
      labels:
        app: bookinfo
    spec:
      containers:
        - name: bookinfo
          image: istio/examples-bookinfo-productpage-v1:1.16.2
          ports:
            - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: bookinfo
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: bookinfo