apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: istio/examples-bookinfo-productpage-v1:1.16.2
        ports:
        - containerPort: 9080
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 9080
    targetPort: 9080
  selector:
    app: productpage